color_calibration_matrix:
  rows: 3
  cols: 3
  data: [1.6016861, -1.0104847, 0.2213647, -0.012442476, 1.0841908, -0.07573348, 0.09123942, -0.8107389, 1.8687756]
  # data: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
  # data: [1.438429, 0.077131405, -0.20208795, -0.5693435, 2.9333502, -0.60181355, -0.3423824, -0.41744354, 2.2011373]
  # data: [2.4276948, 0.21479778, -0.30818, 0.09277014, 1.1962607, -0.09772757, -0.24436986, -0.22239459, 2.099912]
  # data: [1.5758197, -0.0010973621, 0.1050253, -0.9788821, 1.0417756, -0.30694953, 0.21349414, -0.04809823, 1.1955975]
  